spring.application.name=Student_Restfull_API
spring.datasource.url=jdbc:mysql://localhost:3306/student_details_db
spring.datasource.username=root
spring.datasource.password=Dibyendu@3241
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.profiles.active=dev

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true